service: imot2

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    LISTINGS_TABLE_NAME: ${self:custom.ListingsTable.name}
    USER_POOL_ID: { Ref: UserPool }
    USER_POOL_CLIENT_ID: { Ref: UserPoolClient }
  iam:
    role:
      statements:
        - ${file(${self:custom.functions.userCreateLocation}.yml):iam}
        - ${file(${self:custom.functions.userAuthLocation}.yml):iam}
        - ${file(${self:custom.functions.listingCreateLocation}.yml):iam}
        - ${file(${self:custom.functions.listingReadLocation}.yml):iam}

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    UserPool: ${file(src/resources/users.yml):UserPool}
    UserPoolClient: ${file(src/resources/users.yml):UserPoolClient}
    ListingsTable: ${file(src/resources/listings.yml):Table}

functions:
  - ${file(${self:custom.functions.userCreateLocation}.yml):function}
  - ${file(${self:custom.functions.userAuthLocation}.yml):function}
  - ${file(${self:custom.functions.listingCreateLocation}.yml):function}
  - ${file(${self:custom.functions.listingReadLocation}.yml):function}

custom:
  ListingsTable:
    name: !Ref ListingsTable
    arn: !GetAtt ListingsTable.Arn
  UserPool:
    arn: !GetAtt UserPool.Arn
  functions:
    directory: src/functions
    userCreateLocation: ${self:custom.functions.directory}/userCreate
    userAuthLocation: ${self:custom.functions.directory}/userAuth
    listingCreateLocation: ${self:custom.functions.directory}/listingCreate
    listingReadLocation: ${self:custom.functions.directory}/listingRead