function:
  createListing:
    handler: ${self:custom.functions.createListingLocation}.handler
    events:
      - http:
          method: POST
          path: /listing
          cors: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - UserPool
                - Arn
            claims:
              - email

iam:
  Effect: Allow
  Action:
    - dynamodb:PutItem
  Resource:
    - ${self:custom.Imot2Table.arn}